mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('shop.urls')),
    path('admin/', admin.site.urls),
]

shop/urls.py
from django.urls import path

from . import views

app_name = 'shop'
urlpatterns = [
    # ex: /
    path('', views.index, name='index'),
    # ex: cart/
    path('cart/', views.cart, name='cart'),
    # ex: login/
    path("login/", views.login, name="login"),
    # ex: regiser
    path("register/", views.register, name="register"),
    # zarinpal pay-url
    # For start pay
    path('request/', views.send_request, name='request'),
    # For verify payment
    path('verify/', views.verify, name='verify'),
]

shop/models.py
from django.db import models

# Table for store product name nad detail
class Product(models.Model):
    name = models.CharField(max_length=100, verbose_name="نام محصول")
    special = models.BooleanField(verbose_name="محصول ویژه")
    insert_date = models.DateTimeField(verbose_name="ژمان ورود محصول به فروشگاه")
    selling = models.IntegerField(verbose_name="تعداد فروش انجام شده محصول", null=True, blank=True)
    price = models.BigIntegerField(verbose_name="قیمت محصول", null=True, blank=True)
    price_old = models.BigIntegerField(verbose_name="قیمت قبلی محصول", null=True, blank=True)
    image = models.ImageField(upload_to='mysite/shop/static/shop/images', verbose_name='تصویر محصول', null=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "محصول"
        verbose_name_plural= "محصولات"

shop/forms.py
from django import forms

# class for form tools
class RegisterForm(forms.Form):
    full_name = forms.CharField(label='Full name', max_length=100)

shop/views.py
from django.shortcuts import render
from decouple import config

# zarinpal
from django.http import HttpResponse
from django.shortcuts import redirect
import requests
import json
# end zarinpal

from .models import Product

# view for index page : show last post(product)
def index(request):
    # get data from database with special filter or order
    special_product_list = Product.objects.filter(special=1).order_by('-insert_date')
    latest_product_list = Product.objects.order_by('-insert_date')[:8]
    top_selling_product_list = Product.objects.order_by('-selling')[:8]
    # dictionary for send data to template
    context={
        'special_product_list':special_product_list,
        'latest_product_list':latest_product_list,
        'top_selling_product_list':top_selling_product_list,
        }
    return render(request, 'shop/index.html', context)

def cart(request):
    # dictionary for compile template -> variables
    context={}
    # render for send variable and detail to template
    return render(request, 'shop/cart.html', context)

def login(request):
    # dictionary for compile template -> variables
    context={}
    # render for send variable and detail to template
    return render(request, 'shop/login.html', context)

def register(request):
    # dictionary for compile template -> variables
    context={}
    # render for send variable and detail to template
    return render(request, 'shop/register.html', context)

# zarinpal - pay
# for start pay and verify pay in site by zpal
MERCHANT = config('MERCHANT_CODE')
ZP_API_REQUEST = "https://api.zarinpal.com/pg/v4/payment/request.json"
ZP_API_VERIFY = "https://api.zarinpal.com/pg/v4/payment/verify.json"
ZP_API_STARTPAY = "https://www.zarinpal.com/pg/StartPay/{authority}"
amount = 11000  # Rial / Required
description = "تراکنش آزمایشی"  # Required
email = 'm.javidii@yahoo.com'  # Optional
mobile = '09123456789'  # Optional
# Important: need to edit for realy server.
CallbackURL = 'http://127.0.0.1:8000/verify/'


def send_request(request):
    req_data = {
        "merchant_id": MERCHANT,
        "amount": amount,
        "callback_url": CallbackURL,
        "description": description,
        "metadata": {"mobile": mobile, "email": email}
    }
    req_header = {"accept": "application/json",
                  "content-type": "application/json'"}
    req = requests.post(url=ZP_API_REQUEST, data=json.dumps(
        req_data), headers=req_header)
    authority = req.json()['data']['authority']
    if len(req.json()['errors']) == 0:
        return redirect(ZP_API_STARTPAY.format(authority=authority))
    else:
        e_code = req.json()['errors']['code']
        e_message = req.json()['errors']['message']
        return HttpResponse(f"Error code: {e_code}, Error Message: {e_message}")


def verify(request):
    t_status = request.GET.get('Status')
    t_authority = request.GET['Authority']
    if request.GET.get('Status') == 'OK':
        req_header = {"accept": "application/json",
                      "content-type": "application/json'"}
        req_data = {
            "merchant_id": MERCHANT,
            "amount": amount,
            "authority": t_authority
        }
        req = requests.post(url=ZP_API_VERIFY, data=json.dumps(req_data), headers=req_header)
        if len(req.json()['errors']) == 0:
            t_status = req.json()['data']['code']
            if t_status == 100:
                return HttpResponse('Transaction success.\nRefID: ' + str(
                    req.json()['data']['ref_id']
                ))
            elif t_status == 101:
                return HttpResponse('Transaction submitted : ' + str(
                    req.json()['data']['message']
                ))
            else:
                return HttpResponse('Transaction failed.\nStatus: ' + str(
                    req.json()['data']['message']
                ))
        else:
            e_code = req.json()['errors']['code']
            e_message = req.json()['errors']['message']
            return HttpResponse(f"Error code: {e_code}, Error Message: {e_message}")
    else:
        return HttpResponse('Transaction failed or canceled by user')
# end - zarinpal

shop/templates/shop/cart.html
{% extends 'shop/layout/main.html' %}
{% block title %}فروشگاه اینترنتی - سبد خرید{% endblock title %}
{% block body %}{% load static %}
{% include 'shop/partials/header.html' %}

<!-- Main Content -->
<div class="col-12">
<div class="row">
    <div class="col-12 mt-3 text-center text-uppercase">
        <h2>لیست کالاها</h2>
    </div>
</div>
<main class="row">
    <div class="col-12 bg-white py-3 mb-3">
        <div class="row">
            <div class="col-lg-6 col-md-8 col-sm-10 mx-auto table-responsive">
                <form class="row">
                    <div class="col-12">
                        <table class="table table-striped table-hover table-sm">
                            <thead>
                            <tr>
                                <th>نام کالا</th>
                                <th>قیمت</th>
                                <th>تعداد</th>
                                <th>قیمت واحد</th>
                                <th>حذف</th>
                                <th>اضافه</th>
                            </tr>
                            </thead>
                            <tbody id="dynamic">
                            <!-- Script for show list of product from indexdb (browser - database) -->
                            <script>product_list();</script>
                            </tbody>
                            <tfoot>
                            <tr>
                                <th colspan="3" class="text-right">هزینه کل</th>
                                <th id="total-prc">0</th>
                                <th>تومان</th>
                            </tr>
                            </tfoot>
                        </table>
                    </div>
                    <div class="col-12 text-right">
                        <a href="/cart" class="btn btn-outline-secondary mr-3">بروزرسانی</a>
                        <a href="#" class="btn btn-outline-success">تسویه حساب</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</main>
</div>
<!-- Main Content - end -->
{% include 'shop/partials/footer.html' %}
{% endblock body %}

shop/templates/shop/index.html
{% extends 'shop/layout/main.html' %}
{% block title %}فروشگاه اینترنتی - خانه{% endblock title %}
{% block body %}{% load static %}
{% include 'shop/partials/header.html' %}
<!-- Main Content (Dynamic) -->
<div class="col-12">
<main class="row">
{% include 'shop/vendors/slider.html' %}
<!-- Featured Products -->
<div class="col-12 py-3">
    <div class="row">
        <div dir="ltr" class="col-4">
            <a class="btn btn-primary mb-3" href="#carousel-featured_products" role="button" data-bs-slide="next">
                <i class="fa fa-arrow-right"></i>
            </a>
        </div>
        <div class="col-4 text-center">
            <h2>محصولات ویژه</h2>
        </div>
        <div class="col-4">
            <a class="btn btn-primary mb-3 mr-1" href="#carousel-featured_products" role="button" data-bs-slide="prev">
                <i class="fa fa-arrow-left"></i>
            </a>
        </div>
    </div>
    <div class="col-12">
    <div id="carousel-featured_products" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
        
        <div class="carousel-item active">
        <div class="row">

        {% comment %} use divisibleby for div -> post{% endcomment %}
        {% for data in special_product_list %}
        {% if forloop.counter < 9 %}
        {% if forloop.counter|divisibleby:5 %}
        
        </div>
        </div>

        <div class="carousel-item">
        <div class="row">

        {% endif %}
        <!-- Product {{ forloop.counter }} -->
        <div class="col-lg-3 col-sm-6 my-3">
            <div class="col-12 bg-white text-center h-100 product-item">
                <div class="row h-100">
                    <div class="col-12 p-0 mb-3">
                        <a href="#">
                            <img id="img-id-featured_products{{ forloop.counter }}" src="{{ data.image.url }}" class="img-fluid" >
                            <script>img_src("featured", {{ forloop.counter }})</script>
                        </a>
                    </div>
                    <div class="col-12 mb-3">
                        <a href="product.html" class="product-name">{{ data.name }}</a>
                    </div>
                    <div class="col-12 mb-3">
                        <span class="product-price-old">
                        {% if data.price_old is null %}
                        {% else %}
                            {{ data.price_old }} تومان
                        {% endif %}
                        </span>
                        <br>
                        <span class="product-price">
                            {{ data.price }} تومان
                        </span>
                    </div>
                    <div class="col-12 mb-3 align-self-end">
                        <button class="btn btn-outline-dark" type="button" onclick="add_cart({{ data.id }}, '{{ data.name }}', '{{ data.price }}')"><i class="fas fa-cart-plus mr-2"></i>افزودن به سبد خرید</button>
                        <button class="btn btn-outline-dark" type="button" onclick="remove_cart({{ data.id }}, '{{ data.name }}', '{{ data.price }}')">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cart-dash-fill" viewBox="0 0 16 16"><path d="M.5 1a.5.5 0 0 0 0 1h1.11l.401 1.607 1.498 7.985A.5.5 0 0 0 4 12h1a2 2 0 1 0 0 4 2 2 0 0 0 0-4h7a2 2 0 1 0 0 4 2 2 0 0 0 0-4h1a.5.5 0 0 0 .491-.408l1.5-8A.5.5 0 0 0 14.5 3H2.89l-.405-1.621A.5.5 0 0 0 2 1H.5zM6 14a1 1 0 1 1-2 0 1 1 0 0 1 2 0zm7 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0zM6.5 7h4a.5.5 0 0 1 0 1h-4a.5.5 0 0 1 0-1z"/></svg>
                        </button>
                        <hr />
                        <span id="amount-{{ data.id }}"><script>check_cart({{ data.id }});</script></span>
                    </div>
                </div>
            </div>
        </div>
        <!-- Product {{ forloop.counter }} - end-->
        {% endif %}
        {% endfor %}

        </div>
        </div>
    
    </div>
    </div>
    </div>

</div>
<!-- Featured Products - end -->

<div class="col-12">
    <hr>
</div>

<!-- Latest Product -->
<div class="col-12 py-3">
    <div class="row">
        <div dir="ltr" class="col-4">
            <a class="btn btn-primary mb-3" href="#carousel-latest_product" role="button" data-bs-slide="next">
                <i class="fa fa-arrow-right"></i>
            </a>
        </div>
        <div class="col-4 text-center">
            <h2>محصولات جدید</h2>
        </div>
        <div class="col-4">
            <a class="btn btn-primary mb-3 mr-1" href="#carousel-latest_product" role="button" data-bs-slide="prev">
                <i class="fa fa-arrow-left"></i>
            </a>
        </div>
    </div>
    <div class="col-12">
    <div id="carousel-latest_product" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
        
        <div class="carousel-item active">
        <div class="row">

        {% for data in latest_product_list %}
        {% if forloop.counter|divisibleby:5 %}
        
        </div>
        </div>

        <div class="carousel-item">
        <div class="row">

        {% endif %}
        <!-- Product {{ forloop.counter }} -->
        <div class="col-lg-3 col-sm-6 my-3">
            <div class="col-12 bg-white text-center h-100 product-item">
                <div class="row h-100">
                    <div class="col-12 p-0 mb-3">
                        <a href="#">
                            <img id="img-id-latest_products{{ forloop.counter }}" src="{{ data.image.url }}" class="img-fluid" >
                            <script>img_src("latest", {{ forloop.counter }})</script>
                        </a>
                    </div>
                    <div class="col-12 mb-3">
                        <a href="product.html" class="product-name">{{ data.name }}</a>
                    </div>
                    <div class="col-12 mb-3">
                        <span class="product-price-old">
                        {% if data.price_old is null %}
                        {% else %}
                            {{ data.price_old }} تومان
                        {% endif %}
                        </span>
                        <br>
                        <span class="product-price">
                            {{ data.price }} تومان
                        </span>
                    </div>
                    <div class="col-12 mb-3 align-self-end">
                        <button class="btn btn-outline-dark" type="button" onclick="add_cart({{ data.id }}, '{{ data.name }}', '{{ data.price }}')"><i class="fas fa-cart-plus mr-2"></i>افزودن به سبد خرید</button>
                        <button class="btn btn-outline-dark" type="button" onclick="remove_cart({{ data.id }}, '{{ data.name }}', '{{ data.price }}')">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cart-dash-fill" viewBox="0 0 16 16"><path d="M.5 1a.5.5 0 0 0 0 1h1.11l.401 1.607 1.498 7.985A.5.5 0 0 0 4 12h1a2 2 0 1 0 0 4 2 2 0 0 0 0-4h7a2 2 0 1 0 0 4 2 2 0 0 0 0-4h1a.5.5 0 0 0 .491-.408l1.5-8A.5.5 0 0 0 14.5 3H2.89l-.405-1.621A.5.5 0 0 0 2 1H.5zM6 14a1 1 0 1 1-2 0 1 1 0 0 1 2 0zm7 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0zM6.5 7h4a.5.5 0 0 1 0 1h-4a.5.5 0 0 1 0-1z"/></svg>
                        </button>
                        <hr />
                        <span id="amount-{{ data.id }}"><script>check_cart({{ data.id }});</script></span>
                    </div>
                </div>
            </div>
        </div>
        <!-- Product {{ forloop.counter }} - end-->
        {% endfor %}

        </div>
        </div>
    
    </div>
    </div>
    </div>

</div>
<!-- Latest Products - end -->

<div class="col-12">
    <hr>
</div>

<!-- Top Selling Products -->
<div class="col-12 py-3">
    <div class="row">
        <div dir="ltr" class="col-4">
            <a class="btn btn-primary mb-3" href="#carousel-top_selling_products" role="button" data-bs-slide="next">
                <i class="fa fa-arrow-right"></i>
            </a>
        </div>
        <div class="col-4 text-center">
            <h2>محصولات پرفروش</h2>
        </div>
        <div class="col-4">
            <a class="btn btn-primary mb-3 mr-1" href="#carousel-top_selling_products" role="button" data-bs-slide="prev">
                <i class="fa fa-arrow-left"></i>
            </a>
        </div>
    </div>
    <div class="col-12">
    <div id="carousel-top_selling_products" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
        
        <div class="carousel-item active">
        <div class="row">

        {% for data in top_selling_product_list %}
        {% if forloop.counter|divisibleby:5 %}
        
        </div>
        </div>

        <div class="carousel-item">
        <div class="row">

        {% endif %}
        <!-- Product {{ forloop.counter }} -->
        <div class="col-lg-3 col-sm-6 my-3">
            <div class="col-12 bg-white text-center h-100 product-item">
                <div class="row h-100">
                    <div class="col-12 p-0 mb-3">
                        <a href="#">
                            <img id="img-id-top_selling_products{{ forloop.counter }}" src="{{ data.image.url }}" class="img-fluid" >
                            <script>img_src("top_selling", {{ forloop.counter }})</script>
                        </a>
                    </div>
                    <div class="col-12 mb-3">
                        <a href="product.html" class="product-name">{{ data.name }}</a>
                    </div>
                    <div class="col-12 mb-3">
                        <span class="product-price-old">
                        {% if data.price_old is null %}
                        {% else %}
                            {{ data.price_old }} تومان
                        {% endif %}
                        </span>
                        <br>
                        <span class="product-price">
                            {{ data.price }} تومان
                        </span>
                    </div>
                    <div class="col-12 mb-3 align-self-end">
                        <button class="btn btn-outline-dark" type="button" onclick="add_cart({{ data.id }}, '{{ data.name }}', '{{ data.price }}')"><i class="fas fa-cart-plus mr-2"></i>افزودن به سبد خرید</button>
                        <button class="btn btn-outline-dark" type="button" onclick="remove_cart({{ data.id }}, '{{ data.name }}', '{{ data.price }}')">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cart-dash-fill" viewBox="0 0 16 16"><path d="M.5 1a.5.5 0 0 0 0 1h1.11l.401 1.607 1.498 7.985A.5.5 0 0 0 4 12h1a2 2 0 1 0 0 4 2 2 0 0 0 0-4h7a2 2 0 1 0 0 4 2 2 0 0 0 0-4h1a.5.5 0 0 0 .491-.408l1.5-8A.5.5 0 0 0 14.5 3H2.89l-.405-1.621A.5.5 0 0 0 2 1H.5zM6 14a1 1 0 1 1-2 0 1 1 0 0 1 2 0zm7 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0zM6.5 7h4a.5.5 0 0 1 0 1h-4a.5.5 0 0 1 0-1z"/></svg>
                        </button>
                        <hr />
                        <span id="amount-{{ data.id }}"><script>check_cart({{ data.id }});</script></span>
                    </div>
                </div>
            </div>
        </div>
        <!-- Product {{ forloop.counter }} - end-->
        {% endfor %}

        </div>
        </div>
    
    </div>
    </div>
    </div>

</div>
<!-- Latest Products - end -->

{% include 'shop/vendors/banner-end.html' %}

</main>
</div>
<!-- Main Content - end -->
{% include 'shop/partials/footer.html' %}
{% endblock body %}

shop/templates/shop/layout/main.html
{% load static %}<!doctype html>
<html lang="fa" dir="rtl">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.rtl.min.css" integrity="sha384-XfhC/Sid4FIGSXYebcOtcSCRFkd/zZzAMVipf0bNWucloRvcKK2/dpVWodQbQ1Ek" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">

    <!-- My CSS -->
    <link rel="stylesheet" href="{% static 'shop/css/font-awesome-dist/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'shop/css/style.css' %}">

    <!-- My Script -->
    <script type="text/javascript" src="{% static 'shop/js/jquery-dist/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'shop/js/script.js' %}"></script>
    <script type="text/javascript" src="{% static 'shop/js/cart.js' %}"></script>

    <title>{% block title %}{% endblock title %}</title>
  </head>
<body>
{% block body %}{% endblock body %}

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-eMNCOe7tC1doHpGoWe/6oMVemdAVTMs2xqW4mwXrXsW0L84Iytr2wi5v2QjrP/xp" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.min.js" integrity="sha384-cn7l7gDp0eyniUwwAZgrzD06kc/tftFf19TOAs2zVinnD/C7E91j9yyk5//jjpt/" crossorigin="anonymous"></script>
    -->

</body>
</html>

shop/templates/shop/login.html
{% extends 'shop/layout/main.html' %}
{% block title %}فروشگاه اینترنتی - ورود{% endblock title %}
{% block body %}{% load static %}
{% include 'shop/partials/header.html' %}
<!-- Main Content -->
<div class="col-12">
<div class="row">
    <div class="col-12 mt-3 text-center text-uppercase">
        <h2>ورود کاربران</h2>
    </div>
</div>
<main class="row">
    <div class="col-lg-4 col-md-6 col-sm-8 mx-auto bg-white py-3 mb-4">
        <div class="row">
            <div class="col-12">
                <form>
                    <div class="form-group">
                        <label for="email">ایمیل</label>
                        <input style="direction: rtl;" type="email" id="email" class="form-control" required>
                    </div>
                    <div class="form-group">
                        <label for="password">رمز عبور</label>
                        <input type="password" id="password" class="form-control" required>
                    </div>
                    <div class="form-group">
                        <div class="form-check">
                            <input type="checkbox" id="remember" class="form-check-input">
                            <label for="remember" class="form-check-label ml-2">به خاطر بسپار</label>
                        </div>
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-outline-dark">ورود</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</main>
</div>
<!-- Main Content - end -->
{% include 'shop/partials/footer.html' %}
{% endblock body %}

shop/templates/shop/partials/header.html
{% load static %}<!-- Page -->
<div class="container-fluid">
<div class="row min-vh-100">
<!-- Header -->
<div class="col-12">
<header class="row">
{% include 'shop/partials/nav-top.html' %}
<!-- Header toolbar -->
<div class="col-12 bg-white pt-4">
    <div class="row">
        <div class="col-md-4">
            <div class="text-center text-lg-left">
                <a href="/"><img src="{% static 'shop/images/ecommercelogo.png' %}" alt="Ecommerce Store logo" width="150px"></a>
            </div>
        </div>
        <div class="col-md-4 mx-auto mt-4 mt-lg-0 text-lg-left">
            <form action="#">
                <div class="form-group">
                    <div class="input-group">
                        <input type="search" class="form-control border-dark" placeholder="جستجو ..." required>
                        <div class="input-group-append">
                            <button class="btn btn-outline-dark"><i class="fas fa-search"></i></button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
        <div class="col-md-4 text-center text-lg-left header-item-holder">
            <a href="#" class="header-item">
                <i class="fas fa-heart mr-2" style="color:red;"></i>
                <span id="header-favorite">0</span>
            </a>
            <a href="{% url 'shop:cart' %}" class="header-item">
                <i class="fas fa-shopping-bag mr-2" style="color:brown;"></i>
                <span id="header-qty" class="mr-3">0</span>
                <script>cart_amount();</script>
            </a>
                <i class="fas fa-money-bill-wave mr-2" style="color:seagreen;"></i>
                <span id="header-price">0</span>
        </div>
    </div>
{% include 'shop/partials/nav-bar.html' %}
</div>
<!-- Header toolbar - end -->
</header>
</div>
<!-- Header - end -->

shop/templates/shop/partials/nav-bar.html
{% comment %} Hide nav-bar in login and register page {% endcomment %}
{% if not request.get_full_path == "/register/" and not request.get_full_path == "/login/" %}<!-- Nav -->
<div class="row">
    <nav class="navbar navbar-expand-lg navbar-light bg-light col-12">
        <button class="navbar-toggler d-lg-none border-0" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav mx-auto mt-2 mt-lg-0">
                <li class="nav-item active">
                    <a class="nav-link" href="/">خانه<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="electronics" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">کالای دیجیتال</a>
                    <div class="dropdown-menu" aria-labelledby="electronics">
                        <a class="dropdown-item" href="category.html">کامپیوتر</a>
                        <a class="dropdown-item" href="category.html">گوشی موبایل</a>
                        <a class="dropdown-item" href="category.html">تلوزیون</a>
                        <a class="dropdown-item" href="category.html">دوربین</a>
                        <a class="dropdown-item" href="category.html">پروجکتور</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="fashion" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">پوشاک</a>
                    <div class="dropdown-menu" aria-labelledby="fashion">
                        <a class="dropdown-item" href="category.html">آقایان</a>
                        <a class="dropdown-item" href="category.html">خانم ها</a>
                        <a class="dropdown-item" href="category.html">بچه ها</a>
                        <a class="dropdown-item" href="category.html">لوازم</a>
                        <a class="dropdown-item" href="category.html">کفش</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="books" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">کتاب</a>
                    <div class="dropdown-menu" aria-labelledby="books">
                        <a class="dropdown-item" href="category.html">ماجراجویی</a>
                        <a class="dropdown-item" href="category.html">ترسناک</a>
                        <a class="dropdown-item" href="category.html">رمانیک</a>
                        <a class="dropdown-item" href="category.html">کودکان</a>
                        <a class="dropdown-item" href="category.html">تخیلی</a>
                    </div>
                </li>
            </ul>
        </div>
    </nav>
</div>
<!-- Nav - end -->{% endif %}

shop/templates/shop/partials/nav-top.html
<!-- Top Nav - for tools (sign-in or Up and etc...)-->
<div class="col-12 bg-dark py-2 d-md-block">
    <div class="row">
        <div class="col-auto me-auto pt-2 pb-2">
            <ul class="top-nav">
                <li>
                    <a href="{% url 'shop:register' %}"><i class="fas fa-user-edit me-2" style="color:lightskyblue;"></i>ثبت نام</a>
                </li>
                <li>
                    <a href="{% url 'shop:login' %}"><i class="fas fa-sign-in-alt me-2" style="color:red;"></i>ورود</a>
                </li>
            </ul>
        </div>
        <div class="col-auto pt-2">
            <ul class="top-nav">
                <li>
                    <a href="tel:+99-938-123-4102"><i class="fa fa-phone-square me-2" style="color:lime;"></i>99-938-123-4102+</a>
                </li>
                <li>
                    <a href="mailto:mail@mail.com"><i class="fa fa-envelope me-2" style="color:yellow;"></i>mail@mail.com</a>
                </li>
            </ul>
        </div>
    </div>
</div>
<!-- Top Nav - end -->